set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P20} [get_ports fpga_rst]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y18} [get_ports fpga_clk]

# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets start_pg_IBUF]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P5} [get_ports start_pg]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports tx]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K17} [get_ports {led2N4[23]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L13} [get_ports {led2N4[22]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M13} [get_ports {led2N4[21]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K14} [get_ports {led2N4[20]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K13} [get_ports {led2N4[19]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M20} [get_ports {led2N4[18]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N20} [get_ports {led2N4[17]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N19} [get_ports {led2N4[16]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M17} [get_ports {led2N4[15]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M16} [get_ports {led2N4[14]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M15} [get_ports {led2N4[13]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [get_ports {led2N4[12]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L16} [get_ports {led2N4[11]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L15} [get_ports {led2N4[10]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L14} [get_ports {led2N4[9]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J17} [get_ports {led2N4[8]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN F21} [get_ports {led2N4[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G22} [get_ports {led2N4[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN G21} [get_ports {led2N4[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D21} [get_ports {led2N4[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E21} [get_ports {led2N4[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D22} [get_ports {led2N4[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN E22} [get_ports {led2N4[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A21} [get_ports {led2N4[0]}]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y9} [get_ports {switch2N4[23]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W9} [get_ports {switch2N4[22]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y7} [get_ports {switch2N4[21]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y8} [get_ports {switch2N4[20]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB8} [get_ports {switch2N4[19]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA8} [get_ports {switch2N4[18]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V8} [get_ports {switch2N4[17]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V9} [get_ports {switch2N4[16]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB6} [get_ports {switch2N4[15]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB7} [get_ports {switch2N4[14]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V7} [get_ports {switch2N4[13]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AA6} [get_ports {switch2N4[12]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y6} [get_ports {switch2N4[11]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T6} [get_ports {switch2N4[10]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R6} [get_ports {switch2N4[9]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V5} [get_ports {switch2N4[8]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U6} [get_ports {switch2N4[7]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W5} [get_ports {switch2N4[6]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W6} [get_ports {switch2N4[5]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U5} [get_ports {switch2N4[4]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T5} [get_ports {switch2N4[3]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T4} [get_ports {switch2N4[2]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R4} [get_ports {switch2N4[1]}]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN W4} [get_ports {switch2N4[0]}]

set_property PACKAGE_PIN P2 [get_ports {button[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
set_property PACKAGE_PIN P4 [get_ports {button[2]}]
set_property PACKAGE_PIN P1 [get_ports {button[1]}]
set_property PACKAGE_PIN R1 [get_ports {button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTube[0]}]
set_property PACKAGE_PIN F15 [get_ports {digitalTube[7]}]
set_property PACKAGE_PIN F13 [get_ports {digitalTube[6]}]
set_property PACKAGE_PIN F14 [get_ports {digitalTube[5]}]
set_property PACKAGE_PIN F16 [get_ports {digitalTube[4]}]
set_property PACKAGE_PIN E17 [get_ports {digitalTube[3]}]
set_property PACKAGE_PIN C14 [get_ports {digitalTube[2]}]
set_property PACKAGE_PIN C15 [get_ports {digitalTube[1]}]
set_property PACKAGE_PIN E13 [get_ports {digitalTube[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitalTubeEnable[0]}]
set_property PACKAGE_PIN A18 [get_ports {digitalTubeEnable[7]}]
set_property PACKAGE_PIN A20 [get_ports {digitalTubeEnable[6]}]
set_property PACKAGE_PIN B20 [get_ports {digitalTubeEnable[5]}]
set_property PACKAGE_PIN E18 [get_ports {digitalTubeEnable[4]}]
set_property PACKAGE_PIN F18 [get_ports {digitalTubeEnable[3]}]
set_property PACKAGE_PIN D19 [get_ports {digitalTubeEnable[2]}]
set_property PACKAGE_PIN E19 [get_ports {digitalTubeEnable[1]}]
set_property PACKAGE_PIN C19 [get_ports {digitalTubeEnable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardIn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardIn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardIn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardIn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboardOut[0]}]
set_property PACKAGE_PIN L5 [get_ports {keyboardOut[0]}]
set_property PACKAGE_PIN J6 [get_ports {keyboardOut[1]}]
set_property PACKAGE_PIN K6 [get_ports {keyboardOut[2]}]
set_property PACKAGE_PIN M2 [get_ports {keyboardOut[3]}]
set_property PACKAGE_PIN K3 [get_ports {keyboardIn[0]}]
set_property PACKAGE_PIN K4 [get_ports {keyboardIn[3]}]
set_property PACKAGE_PIN L3 [get_ports {keyboardIn[1]}]
set_property PACKAGE_PIN J4 [get_ports {keyboardIn[2]}]
set_property PACKAGE_PIN A19 [get_ports buzzerOut]
set_property IOSTANDARD LVCMOS33 [get_ports buzzerOut]
set_property IOSTANDARD LVCMOS33 [get_ports wdtOut]
set_property IOSTANDARD LVCMOS33 [get_ports pwmOut]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets MEM_WB/CP0/cause_IE]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets MEM_WB/CP0/p_16_out]
